// <auto-generated />
using System;
using EqualFutures.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EqualFutures.Infrastructure.Data.Migrations
{
    [DbContext(typeof(FinancialDbContext))]
    [Migration("20260714012631_AddChildRetirementGroupCount")]
    partial class AddChildRetirementGroupCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("EqualFutures.Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualContribution")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BeneficiaryChildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExpectedReturnOverride")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("FinancialPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxTreatment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FinancialPlanId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("EqualFutures.Domain.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AnnualCostOverride")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CollegeType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DesiredFundingPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedAnnualScholarships")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedCollegeStartYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FinancialPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetirementGroupCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearsOfCollege")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FinancialPlanId");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("EqualFutures.Domain.FinancialPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseholdName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PreferredFairnessMetric")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("EqualFutures.Domain.Liability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("FinancialPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyPayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FinancialPlanId");

                    b.ToTable("Liabilities");
                });

            modelBuilder.Entity("EqualFutures.Domain.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualPensionIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentAge")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EstimatedAnnualSocialSecurity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedAnnualRetirementSpending")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("FinancialPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannedRetirementAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SocialSecurityClaimingAge")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FinancialPlanId");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("EqualFutures.Domain.PlanInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcceptedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcceptedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FinancialPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvitedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("FinancialPlanId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("PlanInvitations");
                });

            modelBuilder.Entity("EqualFutures.Domain.PlanMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("FinancialPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("FinancialPlanId", "UserId")
                        .IsUnique();

                    b.ToTable("PlanMembers");
                });

            modelBuilder.Entity("EqualFutures.Domain.Account", b =>
                {
                    b.HasOne("EqualFutures.Domain.FinancialPlan", null)
                        .WithMany("Accounts")
                        .HasForeignKey("FinancialPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EqualFutures.Domain.Child", b =>
                {
                    b.HasOne("EqualFutures.Domain.FinancialPlan", null)
                        .WithMany("Children")
                        .HasForeignKey("FinancialPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EqualFutures.Domain.FinancialPlan", b =>
                {
                    b.OwnsOne("EqualFutures.Domain.PlanAssumptions", "Assumptions", b1 =>
                        {
                            b1.Property<int>("FinancialPlanId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("EducationInflationRate")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("InflationRate")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT");

                            b1.Property<int>("PlanningHorizonAge")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("PostRetirementReturn")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("PreRetirementReturn")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("SafeWithdrawalRate")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT");

                            b1.HasKey("FinancialPlanId");

                            b1.ToTable("Plans");

                            b1.WithOwner()
                                .HasForeignKey("FinancialPlanId");
                        });

                    b.Navigation("Assumptions")
                        .IsRequired();
                });

            modelBuilder.Entity("EqualFutures.Domain.Liability", b =>
                {
                    b.HasOne("EqualFutures.Domain.FinancialPlan", null)
                        .WithMany("Liabilities")
                        .HasForeignKey("FinancialPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EqualFutures.Domain.Parent", b =>
                {
                    b.HasOne("EqualFutures.Domain.FinancialPlan", null)
                        .WithMany("Parents")
                        .HasForeignKey("FinancialPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EqualFutures.Domain.PlanInvitation", b =>
                {
                    b.HasOne("EqualFutures.Domain.FinancialPlan", null)
                        .WithMany("Invitations")
                        .HasForeignKey("FinancialPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EqualFutures.Domain.PlanMember", b =>
                {
                    b.HasOne("EqualFutures.Domain.FinancialPlan", null)
                        .WithMany("Members")
                        .HasForeignKey("FinancialPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EqualFutures.Domain.FinancialPlan", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Children");

                    b.Navigation("Invitations");

                    b.Navigation("Liabilities");

                    b.Navigation("Members");

                    b.Navigation("Parents");
                });
#pragma warning restore 612, 618
        }
    }
}
